Throw a warning when model weights download fails.

diff --git a/scripts/python_fetch_weights.in b/scripts/python_fetch_weights.in
--- a/scripts/python_fetch_weights.in
+++ b/scripts/python_fetch_weights.in
@@ -3,6 +3,15 @@
 # Get the directory of the currently executing script
 script_dir="$(dirname "$0")"
 
+# Custom function to exit with status 1
+exit_with_error() {
+  echo "One or more download tasks failed. See above error messages."
+  exit 1
+}
+
+# Trap the EXIT signal to call the custom exit function
+trap 'exit_with_error' EXIT
+
 # Call Class Ranker weight download ##############################################
 echo "Attempting to download weights for class ranker..."
 
